# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Sec image url Checker

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install  --user requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run the script
      run: |
        python3 rewriteGoodUrls.py
        echo done
    - name: Push changes
      uses: actions-go/push@v1
      with:
        author-email: "30601311+oliverwk@users.noreply.github.com"
        create-commit: true
        commit-message: "Edited the json for errors in the sec_url"
        force: true
